/**************************************************************************
* Filename:
* ---------
*  ResID\ResID.h : header file
*
* Description:
* ------------
*	
*
* This is auto generated by ResEditor.exe
**************************************************************************/

#if !defined _RESID_RESID_H_
#define _RESID_RESID_H_


#ifdef __cplusplus
    extern "C" {
#endif

#define  ACTION_LEFT    1
#define  ACTION_RIGHT    2
#define  APP_NAME    3
#define  BG_CLOUDS    4
#define  GAME_OVER    5
#define  RESTART_GAME    6


#ifdef __cplusplus
    }
#endif

#endif  /* _RESID_RESID_H_ */

